"""Update Character_model

Revision ID: 5b4e77063c5f
Revises: 525e81ece6d7
Create Date: 2026-08-26 13:34:10.602185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b4e77063c5f'
down_revision: Union[str, Sequence[str], None] = '525e81ece6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    empty_json_object = sa.text("'{}'::jsonb")
    op.add_column(
        'character',
        sa.Column(
            'character_class',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=empty_json_object,
            nullable=False,
        ),
    )
    op.add_column(
        'character',
        sa.Column(
            'inventory',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=empty_json_object,
            nullable=False,
        ),
    )
    op.add_column(
        'character',
        sa.Column(
            'equipment',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=empty_json_object,
            nullable=False,
        ),
    )
    op.alter_column('character', 'race',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using=(
                   "CASE WHEN race IS NULL THEN '{}'::jsonb "
                   "ELSE jsonb_build_object('name', race) END"
               ),
               nullable=False)
    op.alter_column('character', 'buffs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(buffs)',
               existing_nullable=False)
    op.alter_column('character', 'debuffs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(debuffs)',
               existing_nullable=False)
    op.alter_column('character', 'active_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(active_skills)',
               existing_nullable=False)
    op.alter_column('character', 'skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(skills)',
               existing_nullable=False)
    op.alter_column('character', 'spells',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(spells)',
               existing_nullable=False)
    op.alter_column('character', 'character_class', server_default=None)
    op.alter_column('character', 'inventory', server_default=None)
    op.alter_column('character', 'equipment', server_default=None)
    op.drop_column('character', 'weapons_handling')
    op.drop_column('character', 'class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('class_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('weapons_handling', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.alter_column('character', 'spells',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('character', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('character', 'active_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('character', 'debuffs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('character', 'buffs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('character', 'race',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('character', 'equipment')
    op.drop_column('character', 'inventory')
    op.drop_column('character', 'character_class')
    # ### end Alembic commands ###
