"""add spell slots

Revision ID: 91009e2b102a
Revises: 5b4e77063c5f
Create Date: 2026-09-01 14:55:31.649178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91009e2b102a'
down_revision: Union[str, Sequence[str], None] = '5b4e77063c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('spell_slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'spell_slots')
    # ### end Alembic commands ###
